apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
  - name: awscli
    image: cnservices/aws-cli
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
